name: quanlychitieucanhan
description: "Personal Expense Manager â€“ Flutter (Material 3, Provider)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.13.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.1
  sqflite_common_ffi_web: ^0.4.4+4
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/banner_wallet.png
    - assets/images/logo.png
    - assets/images/duy.png
    - assets/images/trong.png
    - assets/images/team_banner.png
    - assets/images/register.png
    - assets/images/profile_banner.png
    - assets/images/user_avatar.png
    - assets/images/change_pwd.png
    - assets/db/schema.sql
    - assets/db/seed.sql
